// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/kamichidu/go-hariti/internal/config/dsl/ast"
)

type enableIfOpt struct {
	expr string
}

var g = &grammar{
	rules: []*rule{
		{
			name: "File",
			pos:  position{line: 14, col: 1, offset: 143},
			expr: &actionExpr{
				pos: position{line: 14, col: 8, offset: 150},
				run: (*parser).callonFile1,
				expr: &seqExpr{
					pos: position{line: 14, col: 8, offset: 150},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 14, col: 8, offset: 150},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 14, col: 11, offset: 153},
							label: "list",
							expr: &zeroOrMoreExpr{
								pos: position{line: 14, col: 16, offset: 158},
								expr: &actionExpr{
									pos: position{line: 14, col: 17, offset: 159},
									run: (*parser).callonFile6,
									expr: &seqExpr{
										pos: position{line: 14, col: 17, offset: 159},
										exprs: []any{
											&labeledExpr{
												pos:   position{line: 14, col: 17, offset: 159},
												label: "decl",
												expr: &ruleRefExpr{
													pos:  position{line: 14, col: 22, offset: 164},
													name: "BundleDecl",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 14, col: 33, offset: 175},
												name: "__",
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 14, col: 59, offset: 201},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "BundleDecl",
			pos:  position{line: 24, col: 1, offset: 396},
			expr: &actionExpr{
				pos: position{line: 24, col: 14, offset: 409},
				run: (*parser).callonBundleDecl1,
				expr: &seqExpr{
					pos: position{line: 24, col: 14, offset: 409},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 24, col: 14, offset: 409},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 24, col: 16, offset: 411},
							val:        "use",
							ignoreCase: false,
							want:       "\"use\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 22, offset: 417},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 24, offset: 419},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 29, offset: 424},
								name: "BundleName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 40, offset: 435},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 43, offset: 438},
							label: "opts",
							expr: &zeroOrMoreExpr{
								pos: position{line: 24, col: 48, offset: 443},
								expr: &actionExpr{
									pos: position{line: 24, col: 49, offset: 444},
									run: (*parser).callonBundleDecl11,
									expr: &seqExpr{
										pos: position{line: 24, col: 49, offset: 444},
										exprs: []any{
											&labeledExpr{
												pos:   position{line: 24, col: 49, offset: 444},
												label: "opt",
												expr: &ruleRefExpr{
													pos:  position{line: 24, col: 53, offset: 448},
													name: "BundleOptions",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 24, col: 67, offset: 462},
												name: "__",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BundleOptions",
			pos:  position{line: 45, col: 1, offset: 902},
			expr: &choiceExpr{
				pos: position{line: 45, col: 17, offset: 918},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 45, col: 17, offset: 918},
						name: "AsOption",
					},
					&ruleRefExpr{
						pos:  position{line: 45, col: 28, offset: 929},
						name: "DependsOption",
					},
					&ruleRefExpr{
						pos:  position{line: 45, col: 44, offset: 945},
						name: "EnableIfOption",
					},
					&ruleRefExpr{
						pos:  position{line: 45, col: 61, offset: 962},
						name: "BuildOption",
					},
				},
			},
		},
		{
			name: "AsOption",
			pos:  position{line: 47, col: 1, offset: 975},
			expr: &actionExpr{
				pos: position{line: 47, col: 12, offset: 986},
				run: (*parser).callonAsOption1,
				expr: &seqExpr{
					pos: position{line: 47, col: 12, offset: 986},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 47, col: 12, offset: 986},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 47, col: 14, offset: 988},
							val:        "as",
							ignoreCase: false,
							want:       "\"as\"",
						},
						&ruleRefExpr{
							pos:  position{line: 47, col: 19, offset: 993},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 47, col: 21, offset: 995},
							label: "alias",
							expr: &ruleRefExpr{
								pos:  position{line: 47, col: 27, offset: 1001},
								name: "BundleName",
							},
						},
					},
				},
			},
		},
		{
			name: "DependsOption",
			pos:  position{line: 51, col: 1, offset: 1045},
			expr: &actionExpr{
				pos: position{line: 51, col: 17, offset: 1061},
				run: (*parser).callonDependsOption1,
				expr: &seqExpr{
					pos: position{line: 51, col: 17, offset: 1061},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 51, col: 17, offset: 1061},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 51, col: 19, offset: 1063},
							val:        "depends",
							ignoreCase: false,
							want:       "\"depends\"",
						},
						&ruleRefExpr{
							pos:  position{line: 51, col: 29, offset: 1073},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 51, col: 32, offset: 1076},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 51, col: 36, offset: 1080},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 51, col: 39, offset: 1083},
							label: "names",
							expr: &ruleRefExpr{
								pos:  position{line: 51, col: 45, offset: 1089},
								name: "DependsList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 51, col: 57, offset: 1101},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 51, col: 60, offset: 1104},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "DependsList",
			pos:  position{line: 55, col: 1, offset: 1132},
			expr: &actionExpr{
				pos: position{line: 55, col: 15, offset: 1146},
				run: (*parser).callonDependsList1,
				expr: &labeledExpr{
					pos:   position{line: 55, col: 15, offset: 1146},
					label: "list",
					expr: &zeroOrMoreExpr{
						pos: position{line: 55, col: 20, offset: 1151},
						expr: &actionExpr{
							pos: position{line: 55, col: 21, offset: 1152},
							run: (*parser).callonDependsList4,
							expr: &seqExpr{
								pos: position{line: 55, col: 21, offset: 1152},
								exprs: []any{
									&labeledExpr{
										pos:   position{line: 55, col: 21, offset: 1152},
										label: "name",
										expr: &ruleRefExpr{
											pos:  position{line: 55, col: 26, offset: 1157},
											name: "BundleName",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 55, col: 37, offset: 1168},
										name: "__",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EnableIfOption",
			pos:  position{line: 65, col: 1, offset: 1349},
			expr: &actionExpr{
				pos: position{line: 65, col: 18, offset: 1366},
				run: (*parser).callonEnableIfOption1,
				expr: &seqExpr{
					pos: position{line: 65, col: 18, offset: 1366},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 65, col: 18, offset: 1366},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 65, col: 20, offset: 1368},
							val:        "enable_if",
							ignoreCase: false,
							want:       "\"enable_if\"",
						},
						&ruleRefExpr{
							pos:  position{line: 65, col: 32, offset: 1380},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 65, col: 34, offset: 1382},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 65, col: 39, offset: 1387},
								name: "StringLiteral",
							},
						},
					},
				},
			},
		},
		{
			name: "BuildOption",
			pos:  position{line: 69, col: 1, offset: 1452},
			expr: &actionExpr{
				pos: position{line: 69, col: 15, offset: 1466},
				run: (*parser).callonBuildOption1,
				expr: &seqExpr{
					pos: position{line: 69, col: 15, offset: 1466},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 69, col: 15, offset: 1466},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 69, col: 17, offset: 1468},
							val:        "build",
							ignoreCase: false,
							want:       "\"build\"",
						},
						&ruleRefExpr{
							pos:  position{line: 69, col: 25, offset: 1476},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 69, col: 28, offset: 1479},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 69, col: 32, offset: 1483},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 69, col: 35, offset: 1486},
							label: "blocks",
							expr: &ruleRefExpr{
								pos:  position{line: 69, col: 42, offset: 1493},
								name: "BuildBlockList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 69, col: 57, offset: 1508},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 69, col: 60, offset: 1511},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "BuildBlockList",
			pos:  position{line: 73, col: 1, offset: 1540},
			expr: &actionExpr{
				pos: position{line: 73, col: 18, offset: 1557},
				run: (*parser).callonBuildBlockList1,
				expr: &labeledExpr{
					pos:   position{line: 73, col: 18, offset: 1557},
					label: "list",
					expr: &zeroOrMoreExpr{
						pos: position{line: 73, col: 23, offset: 1562},
						expr: &actionExpr{
							pos: position{line: 73, col: 24, offset: 1563},
							run: (*parser).callonBuildBlockList4,
							expr: &seqExpr{
								pos: position{line: 73, col: 24, offset: 1563},
								exprs: []any{
									&labeledExpr{
										pos:   position{line: 73, col: 24, offset: 1563},
										label: "block",
										expr: &ruleRefExpr{
											pos:  position{line: 73, col: 30, offset: 1569},
											name: "BuildBlock",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 73, col: 41, offset: 1580},
										name: "__",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BuildBlock",
			pos:  position{line: 83, col: 1, offset: 1782},
			expr: &actionExpr{
				pos: position{line: 83, col: 14, offset: 1795},
				run: (*parser).callonBuildBlock1,
				expr: &seqExpr{
					pos: position{line: 83, col: 14, offset: 1795},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 83, col: 14, offset: 1795},
							val:        "on",
							ignoreCase: false,
							want:       "\"on\"",
						},
						&ruleRefExpr{
							pos:  position{line: 83, col: 19, offset: 1800},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 83, col: 21, offset: 1802},
							label: "osName",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 28, offset: 1809},
								name: "OSName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 83, col: 35, offset: 1816},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 83, col: 38, offset: 1819},
							label: "cmds",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 43, offset: 1824},
								name: "BuildCommandList",
							},
						},
					},
				},
			},
		},
		{
			name: "BuildCommandList",
			pos:  position{line: 90, col: 1, offset: 1936},
			expr: &actionExpr{
				pos: position{line: 90, col: 20, offset: 1955},
				run: (*parser).callonBuildCommandList1,
				expr: &labeledExpr{
					pos:   position{line: 90, col: 20, offset: 1955},
					label: "list",
					expr: &oneOrMoreExpr{
						pos: position{line: 90, col: 25, offset: 1960},
						expr: &actionExpr{
							pos: position{line: 90, col: 26, offset: 1961},
							run: (*parser).callonBuildCommandList4,
							expr: &seqExpr{
								pos: position{line: 90, col: 26, offset: 1961},
								exprs: []any{
									&labeledExpr{
										pos:   position{line: 90, col: 26, offset: 1961},
										label: "cmd",
										expr: &ruleRefExpr{
											pos:  position{line: 90, col: 30, offset: 1965},
											name: "BuildCommand",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 90, col: 43, offset: 1978},
										name: "__",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BuildCommand",
			pos:  position{line: 100, col: 1, offset: 2154},
			expr: &actionExpr{
				pos: position{line: 100, col: 16, offset: 2169},
				run: (*parser).callonBuildCommand1,
				expr: &seqExpr{
					pos: position{line: 100, col: 16, offset: 2169},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 100, col: 16, offset: 2169},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 20, offset: 2173},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 100, col: 22, offset: 2175},
							label: "cmd",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 26, offset: 2179},
								name: "CommandLine",
							},
						},
					},
				},
			},
		},
		{
			name: "CommandLine",
			pos:  position{line: 104, col: 1, offset: 2222},
			expr: &actionExpr{
				pos: position{line: 104, col: 15, offset: 2236},
				run: (*parser).callonCommandLine1,
				expr: &oneOrMoreExpr{
					pos: position{line: 104, col: 15, offset: 2236},
					expr: &charClassMatcher{
						pos:        position{line: 104, col: 15, offset: 2236},
						val:        "[^\\r\\n]",
						chars:      []rune{'\r', '\n'},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name: "BundleName",
			pos:  position{line: 108, col: 1, offset: 2297},
			expr: &actionExpr{
				pos: position{line: 108, col: 14, offset: 2310},
				run: (*parser).callonBundleName1,
				expr: &labeledExpr{
					pos:   position{line: 108, col: 14, offset: 2310},
					label: "chars",
					expr: &oneOrMoreExpr{
						pos: position{line: 108, col: 20, offset: 2316},
						expr: &charClassMatcher{
							pos:        position{line: 108, col: 20, offset: 2316},
							val:        "[a-zA-Z0-9_./-]",
							chars:      []rune{'_', '.', '/', '-'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "OSName",
			pos:  position{line: 112, col: 1, offset: 2366},
			expr: &actionExpr{
				pos: position{line: 112, col: 10, offset: 2375},
				run: (*parser).callonOSName1,
				expr: &labeledExpr{
					pos:   position{line: 112, col: 10, offset: 2375},
					label: "chars",
					expr: &oneOrMoreExpr{
						pos: position{line: 112, col: 16, offset: 2381},
						expr: &charClassMatcher{
							pos:        position{line: 112, col: 16, offset: 2381},
							val:        "[a-zA-Z0-9_*.-]",
							chars:      []rune{'_', '*', '.', '-'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 116, col: 1, offset: 2431},
			expr: &choiceExpr{
				pos: position{line: 116, col: 17, offset: 2447},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 116, col: 17, offset: 2447},
						name: "DoubleQuotedString",
					},
					&ruleRefExpr{
						pos:  position{line: 116, col: 38, offset: 2468},
						name: "SingleQuotedString",
					},
				},
			},
		},
		{
			name: "DoubleQuotedString",
			pos:  position{line: 118, col: 1, offset: 2488},
			expr: &actionExpr{
				pos: position{line: 118, col: 22, offset: 2509},
				run: (*parser).callonDoubleQuotedString1,
				expr: &seqExpr{
					pos: position{line: 118, col: 22, offset: 2509},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 118, col: 22, offset: 2509},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 118, col: 26, offset: 2513},
							expr: &charClassMatcher{
								pos:        position{line: 118, col: 26, offset: 2513},
								val:        "[^\"\\r\\n]",
								chars:      []rune{'"', '\r', '\n'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 118, col: 36, offset: 2523},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "SingleQuotedString",
			pos:  position{line: 122, col: 1, offset: 2577},
			expr: &actionExpr{
				pos: position{line: 122, col: 22, offset: 2598},
				run: (*parser).callonSingleQuotedString1,
				expr: &seqExpr{
					pos: position{line: 122, col: 22, offset: 2598},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 122, col: 22, offset: 2598},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 122, col: 26, offset: 2602},
							expr: &charClassMatcher{
								pos:        position{line: 122, col: 26, offset: 2602},
								val:        "[^'\\r\\n]",
								chars:      []rune{'\'', '\r', '\n'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 122, col: 36, offset: 2612},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 126, col: 1, offset: 2666},
			expr: &zeroOrMoreExpr{
				pos: position{line: 126, col: 5, offset: 2670},
				expr: &charClassMatcher{
					pos:        position{line: 126, col: 5, offset: 2670},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 128, col: 1, offset: 2678},
			expr: &zeroOrMoreExpr{
				pos: position{line: 128, col: 6, offset: 2683},
				expr: &charClassMatcher{
					pos:        position{line: 128, col: 6, offset: 2683},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 130, col: 1, offset: 2695},
			expr: &notExpr{
				pos: position{line: 130, col: 7, offset: 2701},
				expr: &anyMatcher{
					line: 130, col: 8, offset: 2702,
				},
			},
		},
	},
}

func (c *current) onFile6(decl any) (any, error) {
	return decl, nil
}

func (p *parser) callonFile6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFile6(stack["decl"])
}

func (c *current) onFile1(list any) (any, error) {
	var decls []ast.BundleDecl
	if list != nil {
		for _, item := range list.([]interface{}) {
			decls = append(decls, item.(ast.BundleDecl))
		}
	}
	return &ast.File{Bundles: decls}, nil
}

func (p *parser) callonFile1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFile1(stack["list"])
}

func (c *current) onBundleDecl11(opt any) (any, error) {
	return opt, nil
}

func (p *parser) callonBundleDecl11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBundleDecl11(stack["opt"])
}

func (c *current) onBundleDecl1(name, opts any) (any, error) {
	decl := ast.BundleDecl{
		Use: name.(string),
	}
	if opts != nil {
		for _, opt := range opts.([]interface{}) {
			switch v := opt.(type) {
			case string:
				decl.Aliases = append(decl.Aliases, v)
			case []string:
				decl.Depends = append(decl.Depends, v...)
			case enableIfOpt:
				decl.EnableIf = v.expr
			case []ast.BuildBlock:
				decl.Build = append(decl.Build, v...)
			}
		}
	}
	return decl, nil
}

func (p *parser) callonBundleDecl1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBundleDecl1(stack["name"], stack["opts"])
}

func (c *current) onAsOption1(alias any) (any, error) {
	return alias.(string), nil
}

func (p *parser) callonAsOption1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAsOption1(stack["alias"])
}

func (c *current) onDependsOption1(names any) (any, error) {
	return names, nil
}

func (p *parser) callonDependsOption1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDependsOption1(stack["names"])
}

func (c *current) onDependsList4(name any) (any, error) {
	return name, nil
}

func (p *parser) callonDependsList4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDependsList4(stack["name"])
}

func (c *current) onDependsList1(list any) (any, error) {
	var names []string
	if list != nil {
		for _, item := range list.([]interface{}) {
			names = append(names, item.(string))
		}
	}
	return names, nil
}

func (p *parser) callonDependsList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDependsList1(stack["list"])
}

func (c *current) onEnableIfOption1(expr any) (any, error) {
	return enableIfOpt{expr: expr.(string)}, nil
}

func (p *parser) callonEnableIfOption1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnableIfOption1(stack["expr"])
}

func (c *current) onBuildOption1(blocks any) (any, error) {
	return blocks, nil
}

func (p *parser) callonBuildOption1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBuildOption1(stack["blocks"])
}

func (c *current) onBuildBlockList4(block any) (any, error) {
	return block, nil
}

func (p *parser) callonBuildBlockList4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBuildBlockList4(stack["block"])
}

func (c *current) onBuildBlockList1(list any) (any, error) {
	var blocks []ast.BuildBlock
	if list != nil {
		for _, item := range list.([]interface{}) {
			blocks = append(blocks, item.(ast.BuildBlock))
		}
	}
	return blocks, nil
}

func (p *parser) callonBuildBlockList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBuildBlockList1(stack["list"])
}

func (c *current) onBuildBlock1(osName, cmds any) (any, error) {
	return ast.BuildBlock{
		OS:       osName.(string),
		Commands: cmds.([]string),
	}, nil
}

func (p *parser) callonBuildBlock1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBuildBlock1(stack["osName"], stack["cmds"])
}

func (c *current) onBuildCommandList4(cmd any) (any, error) {
	return cmd, nil
}

func (p *parser) callonBuildCommandList4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBuildCommandList4(stack["cmd"])
}

func (c *current) onBuildCommandList1(list any) (any, error) {
	var cmds []string
	if list != nil {
		for _, item := range list.([]interface{}) {
			cmds = append(cmds, item.(string))
		}
	}
	return cmds, nil
}

func (p *parser) callonBuildCommandList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBuildCommandList1(stack["list"])
}

func (c *current) onBuildCommand1(cmd any) (any, error) {
	return cmd.(string), nil
}

func (p *parser) callonBuildCommand1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBuildCommand1(stack["cmd"])
}

func (c *current) onCommandLine1() (any, error) {
	return strings.TrimSpace(string(c.text)), nil
}

func (p *parser) callonCommandLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommandLine1()
}

func (c *current) onBundleName1(chars any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonBundleName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBundleName1(stack["chars"])
}

func (c *current) onOSName1(chars any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonOSName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOSName1(stack["chars"])
}

func (c *current) onDoubleQuotedString1() (any, error) {
	return string(c.text[1 : len(c.text)-1]), nil
}

func (p *parser) callonDoubleQuotedString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleQuotedString1()
}

func (c *current) onSingleQuotedString1() (any, error) {
	return string(c.text[1 : len(c.text)-1]), nil
}

func (p *parser) callonSingleQuotedString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleQuotedString1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
