package subcmd

import (
	"fmt"
	"io"
	"os"
	"time"

	"github.com/kamichidu/go-hariti"
	"github.com/urfave/cli"
)

func deployAction(c *cli.Context) error {
	har := c.App.Metadata["hariti"].(*hariti.Hariti)

	var w io.Writer
	if ofile := c.String("output"); ofile == "-" {
		w = c.App.Writer
	} else {
		fw, err := os.Create(ofile)
		if err != nil {
			return cli.NewExitError(err, 128)
		}
		defer fw.Close()
		w = fw
	}

	header := []string{
		fmt.Sprintf(`" Generated by %s %s at %s`, c.App.Name, c.App.Version, time.Now()),
		`" DO NOT EDIT THIS FILE`,
	}
	if err := har.WriteScript(w, header); err != nil {
		return cli.NewExitError(err, 1)
	}
	return nil
}

func init() {
	Commands = append(Commands, cli.Command{
		Name:      "deploy",
		Usage:     "Generate vim script for setting-up runtimepath",
		ArgsUsage: "{bundles file}",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "output,o",
				Usage: "Output `FILE`",
				Value: "-",
			},
		},
		Action: deployAction,
	})
}
